FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    curl \
    net-tools \
    iproute2 \
    dnsutils \
    vim \
    jq \
    openssl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root
CMD ["sleep", "infinity"]
